<a href="https://colab.research.google.com/github/karthikeyanthanigai/German-credit-card-problem/blob/master/credit_card_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Import the Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

![alt text](https://medici-prod.s3-us-west-2.amazonaws.com/uploads/are-credit-cards-the-same-in-the-us-and-canada.jpg)

In [0]:
#Importing the Dataset
Dataset = pd.read_csv("german_credit_data_dataset.csv")
X = Dataset.iloc[:, :-1].values
y = Dataset.iloc[:, [-1]].values

In [0]:
#list all the string value and convert them in to int values!!
#Note we are doing only labelencoder 
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[:, 0] = labelencoder.fit_transform(X[:, 0])

X[:, 2] = labelencoder.fit_transform(X[:, 2])

X[:, 3] = labelencoder.fit_transform(X[:, 3])

X[:, 5] = labelencoder.fit_transform(X[:, 5])

X[:, 6] = labelencoder.fit_transform(X[:, 6])

X[:, 8] = labelencoder.fit_transform(X[:, 8])

X[:, 9] = labelencoder.fit_transform(X[:, 9])

X[:, 11] = labelencoder.fit_transform(X[:, 11])

X[:, 13] = labelencoder.fit_transform(X[:, 13])

X[:, 14] = labelencoder.fit_transform(X[:, 14])

X[:, 16] = labelencoder.fit_transform(X[:, 16])

X[:, 18] = labelencoder.fit_transform(X[:, 18])

X[:, 19] = labelencoder.fit_transform(X[:, 19])


In [4]:
#new X values:
print(X)


[[0 6 4 ... 1 1 0]
 [1 48 2 ... 1 0 0]
 [3 12 4 ... 2 0 0]
 ...
 [3 12 2 ... 1 0 0]
 [0 45 2 ... 1 1 0]
 [1 45 4 ... 1 0 0]]


In [0]:
#feature scale our independent variables 
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [0]:
#Splitting the dataset into training and testing set's
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=0, shuffle=True)


In [7]:
#Logistic Regression model. 
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1000, random_state =0, solver='liblinear',multi_class='ovr')
classifier.fit(X_train, y_train)

#predict with test set
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:

#evaluating our model.
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
acc_train = accuracy_score(y_train, classifier.predict(X_train))
f1_train = f1_score(y_train, classifier.predict(X_train), average= 'weighted')

print("Traing set results")
print("ACCURACY for train set",acc_train)
print("F1 SCORE for train set",f1_train)

Traing set results
ACCURACY for train set 0.7757142857142857
F1 SCORE for train set 0.7636969195226275


In [9]:
#evaluate with test set
acc_test = accuracy_score(y_test, y_pred)
f1_test = f1_score(y_test, y_pred, average= 'weighted')

print("Test set results")
print("ACCURACY for test set",acc_test)
print("F1 SCORE for test set",f1_test)

Test set results
ACCURACY for test set 0.7666666666666667
F1 SCORE for test set 0.7631162825389721


In [10]:
#Confusion Matrix 
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[183  31]
 [ 39  47]]
